### ISSUE TITLE
Queries on sub-objects?

### ISSUE THREAD

**Issue by tahpot** [oxdev03/lucene-kit#21]
I have this object:

```
{
 id: 1,
 content: 'hello world',
 attachments: [{
  id: 'a-1',
  content: 'attachment content 1'
 }, {
  id: 'a-1',
  content: 'attachment content 2'
 }]
}
```

Is it possible to search on `attachments.content`?

**Comment by oxdev03** [comment]
Currently only possible using https://github.com/oxdev03/lucene-kit?tab=readme-ov-file#searchfilter. 
E.g. 
key.*.keyinarray
